import { useEffect, useState } from 'react';
import { formatMarketPrice, getMarket, getStoredMarket, MARKETS, setStoredMarket, type MarketCode } from '../lib/pricingMatrix';

type PricingGroup = { title: string; items: string[] };
type PricingPackage = { id: string; name: string; price: string; currency: string; billing_label: string; tone: 'starter' | 'growth' | 'premium'; popular: boolean; groups: PricingGroup[]; market_prices: Partial<Record<MarketCode, number>>; sort_order: number };
type PricingState = PricingPackage[] | null;
const WHATSAPP = 'https://wa.me/201556764804?text=';

function esc(value: unknown) { return String(value).replace(/[&<>\"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;', "'": '&#39;' })[char] ?? char); }
function localPackagePrice(pkg: PricingPackage, market: MarketCode) { const configured = Number(pkg.market_prices?.[market]); return Number.isFinite(configured) && configured > 0 ? configured : (Number(pkg.price) || 0); }
function cardMarkup(pkg: PricingPackage, market: MarketCode) {
  const marketConfig = getMarket(market); const localPrice = localPackagePrice(pkg, market);
  const groups = pkg.groups.map((group) => `<div class="zero-one-package__group"><h3>${esc(group.title)}</h3><ul class="zero-one-package__list">${group.items.map((item) => `<li>${esc(item)}</li>`).join('')}</ul></div>`).join('');
  const featureCount = pkg.groups.reduce((total, group) => total + group.items.length, 0);
  const message = encodeURIComponent(`Hi ZERO ONE, I'm interested in the ${pkg.name} package in ${marketConfig.country}. I'd like to discuss the next steps.`);
  const toneLabel = pkg.tone === 'premium' ? 'Premium' : pkg.tone === 'growth' ? 'Growth' : 'Starter';
  return `<article class="zero-one-package zero-one-package--${esc(pkg.tone)}" data-package-name="${esc(pkg.name)}"><span class="zero-one-package__glow" aria-hidden="true"></span>${pkg.popular ? '<span class="zero-one-package__popular">Most Popular</span>' : ''}<div class="zero-one-package__signal"><span class="zero-one-package__signal-dot"></span><span>${toneLabel} package</span></div><div class="zero-one-package__top"><span class="zero-one-package__name">${esc(pkg.name)}</span><span class="zero-one-package__tag">${esc(pkg.billing_label)}</span></div><div class="zero-one-package__price"><strong>${esc(formatMarketPrice(localPrice, market))}</strong><span>${esc(marketConfig.currency)} / ${esc(pkg.billing_label)}</span></div><div class="zero-one-package__details-head"><span><b>${featureCount}</b> included items</span><button type="button" class="zero-one-package__details-toggle" aria-expanded="false" data-pricing-details-toggle><span class="zero-one-package__details-toggle-label">View what’s included</span><span class="zero-one-package__details-toggle-icon" aria-hidden="true">+</span></button></div><div class="zero-one-package__details" aria-hidden="true"><div class="zero-one-package__details-inner">${groups}</div></div><a class="zero-one-package__cta" href="${WHATSAPP}${message}" target="_blank" rel="noopener noreferrer">Start with ${esc(pkg.name)}</a></article>`;
}
function publishPackageSignal(pkg: PricingPackage) { window.dispatchEvent(new CustomEvent('zero-one:pricing-focus', { detail: { name: pkg.name, tone: pkg.tone, popular: pkg.popular } })); }
function setupDetailToggle(grid: Element) { const toggle = grid.querySelector<HTMLButtonElement>('[data-pricing-details-toggle]'); const details = grid.querySelector<HTMLElement>('.zero-one-package__details'); if (!toggle || !details) return; toggle.addEventListener('click', () => { const open = toggle.getAttribute('aria-expanded') === 'true'; toggle.setAttribute('aria-expanded', String(!open)); details.setAttribute('aria-hidden', String(open)); details.classList.toggle('is-open', !open); const label = toggle.querySelector('.zero-one-package__details-toggle-label'); if (label) label.textContent = open ? 'View what’s included' : 'Hide details'; }); }
function setupCardTilt(grid: Element) { const packageCard = grid.querySelector<HTMLElement>('.zero-one-package'); if (!packageCard || !window.matchMedia('(pointer: fine)').matches) return; packageCard.addEventListener('mousemove', (event) => { const rect = packageCard.getBoundingClientRect(); const x = (event.clientX - rect.left) / rect.width - 0.5; const y = (event.clientY - rect.top) / rect.height - 0.5; packageCard.style.setProperty('--tilt-x', `${(-y * 3).toFixed(2)}deg`); packageCard.style.setProperty('--tilt-y', `${(x * 3).toFixed(2)}deg`); packageCard.style.setProperty('--spot-x', `${(x + 0.5) * 100}%`); packageCard.style.setProperty('--spot-y', `${(y + 0.5) * 100}%`); }); packageCard.addEventListener('mouseleave', () => { packageCard.style.setProperty('--tilt-x', '0deg'); packageCard.style.setProperty('--tilt-y', '0deg'); packageCard.style.setProperty('--spot-x', '50%'); packageCard.style.setProperty('--spot-y', '34%'); }); packageCard.addEventListener('mouseenter', () => { const name = packageCard.dataset.packageName; if (!name) return; const tone = packageCard.classList.contains('zero-one-package--premium') ? 'premium' : packageCard.classList.contains('zero-one-package--growth') ? 'growth' : 'starter'; publishPackageSignal({ id: '', name, price: '', currency: '', billing_label: '', tone, popular: false, groups: [], market_prices: {}, sort_order: 0 }); }); }
function renderPricing(section: HTMLElement, packages: PricingPackage[], market: MarketCode) {
  const grid = section.querySelector('.zero-one-pricing__grid'); if (!grid) return; const sorted = [...packages].sort((a, b) => a.sort_order - b.sort_order); let activeIndex = 0;
  const render = (direction: 'next' | 'prev' | 'direct' = 'direct') => { const pkg = sorted[activeIndex]; if (!pkg) return; grid.innerHTML = `<div class="zero-one-pricing-carousel" role="region" aria-label="Pricing packages" aria-live="polite"><button type="button" class="zero-one-pricing-carousel__arrow zero-one-pricing-carousel__arrow--prev" data-pricing-prev aria-label="Previous package">←</button><div class="zero-one-pricing-carousel__viewport"><div class="zero-one-pricing-carousel__card" data-direction="${direction}">${cardMarkup(pkg, market)}</div></div><button type="button" class="zero-one-pricing-carousel__arrow zero-one-pricing-carousel__arrow--next" data-pricing-next aria-label="Next package">→</button></div><div class="zero-one-pricing-carousel__footer"><div class="zero-one-pricing-carousel__dots" role="tablist" aria-label="Select pricing package">${sorted.map((item, index) => `<button type="button" role="tab" aria-selected="${index === activeIndex}" aria-label="View ${esc(item.name)} package" class="zero-one-pricing-carousel__dot${index === activeIndex ? ' is-active' : ''}" data-pricing-index="${index}"><span>${String(index + 1).padStart(2, '0')}</span></button>`).join('')}</div><div class="zero-one-pricing-carousel__counter"><strong>${String(activeIndex + 1).padStart(2, '0')}</strong><span>/ ${String(sorted.length).padStart(2, '0')}</span></div></div>`; setupDetailToggle(grid); setupCardTilt(grid); grid.querySelector('[data-pricing-prev]')?.addEventListener('click', () => { activeIndex = (activeIndex - 1 + sorted.length) % sorted.length; publishPackageSignal(sorted[activeIndex]); render('prev'); }); grid.querySelector('[data-pricing-next]')?.addEventListener('click', () => { activeIndex = (activeIndex + 1) % sorted.length; publishPackageSignal(sorted[activeIndex]); render('next'); }); grid.querySelectorAll<HTMLElement>('[data-pricing-index]').forEach((button) => button.addEventListener('click', () => { const nextIndex = Number(button.dataset.pricingIndex ?? 0); const nextDirection = nextIndex >= activeIndex ? 'next' : 'prev'; activeIndex = nextIndex; publishPackageSignal(sorted[activeIndex]); render(nextDirection); })); section.querySelector('.zero-one-pricing__carousel-intro')?.remove(); };
  grid.className = 'zero-one-pricing__grid zero-one-pricing__grid--carousel'; render();
}
function setupMarketSelector(section: HTMLElement, packages: PricingPackage[], initialMarket: MarketCode) {
  let market = initialMarket; const intro = section.querySelector('.zero-one-pricing__intro'); if (!intro || intro.querySelector('[data-market-selector]')) return;
  const selector = document.createElement('div'); selector.className = 'zero-one-market-selector'; selector.setAttribute('data-market-selector', 'true'); selector.innerHTML = `<span class="zero-one-market-selector__label">Your market</span><div class="zero-one-market-selector__options" role="tablist" aria-label="Choose your market">${MARKETS.map((item) => `<button type="button" role="tab" aria-selected="${item.code === market}" class="zero-one-market-selector__option${item.code === market ? ' is-active' : ''}" data-market-code="${item.code}"><span>${item.flag}</span><strong>${item.country}</strong><small>${item.currency}</small></button>`).join('')}</div>`; intro.appendChild(selector);
  selector.querySelectorAll<HTMLButtonElement>('[data-market-code]').forEach((button) => button.addEventListener('click', () => { const code = button.dataset.marketCode as MarketCode; if (!MARKETS.some((item) => item.code === code)) return; market = code; setStoredMarket(code); selector.querySelectorAll('[data-market-code]').forEach((item) => { item.classList.toggle('is-active', (item as HTMLElement).dataset.marketCode === market); item.setAttribute('aria-selected', String((item as HTMLElement).dataset.marketCode === market)); }); renderPricing(section, packages, market); }));
  renderPricing(section, packages, market);
}
export default function RemotePricingSync() {
  const [packages, setPackages] = useState<PricingState>(null);
  useEffect(() => { const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined; const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined; if (!supabaseUrl || !supabaseKey || (window.location.pathname !== '/' && window.location.pathname !== '')) return; let active = true; fetch(`${supabaseUrl}/rest/v1/pricing_packages?select=id,name,price,currency,billing_label,tone,popular,groups,market_prices,sort_order&order=sort_order.asc,created_at.desc`, { headers: { apikey: supabaseKey, Authorization: `Bearer ${supabaseKey}` } }).then(async (response) => { if (!response.ok) throw new Error('Pricing request failed'); return response.json() as Promise<PricingPackage[]>; }).then((data) => { if (active) setPackages(data); }).catch(() => undefined); return () => { active = false; }; }, []);
  useEffect(() => { if (!packages) return; let attempts = 0; const run = () => { const section = document.getElementById('zero-one-pricing'); if (!section) { if (attempts++ < 40) window.setTimeout(run, 100); return; } if (!section.querySelector('[data-market-selector]')) setupMarketSelector(section, packages, getStoredMarket()); if (attempts++ < 40) window.setTimeout(() => { const current = getStoredMarket(); if (section.querySelector('[data-market-selector]')) { const grid = section.querySelector('.zero-one-pricing__grid'); if (grid && !grid.querySelector('.zero-one-pricing-carousel')) renderPricing(section, packages, current); } }, 100); }; run(); }, [packages]);
  useEffect(() => { const onMarketChange = () => { if (!packages) return; const section = document.getElementById('zero-one-pricing'); if (section) renderPricing(section, packages, getStoredMarket()); }; window.addEventListener('zero-one:market-change', onMarketChange); return () => window.removeEventListener('zero-one:market-change', onMarketChange); }, [packages]);
  return null;
}
