import { useEffect, useMemo, useState } from 'react';
import { Clock3, GripVertical, LogOut, Pencil, Plus, Save, UserRound, X } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../auth/AuthProvider';
import './EmployeeTaskBoard.css';

type Status='client_requests'|'in_progress'|'review'|'completed';
type Priority='low'|'normal'|'high'|'urgent';
type Profile={id:string;name:string;email:string|null;role:'employee'|'admin';access_enabled:boolean};
type Task={id:string;title:string;description:string;assignee_id:string|null;status:Status;priority:Priority;due_date:string|null;sort_order:number};
const columns:{id:Status;label:string;sub:string}[]=[{id:'client_requests',label:'Client Requests',sub:'New work to pick up'},{id:'in_progress',label:'In Progress',sub:'Currently being worked on'},{id:'review',label:'Review',sub:'Waiting for approval'},{id:'completed',label:'Completed',sub:'Approved work'}];
const priorities:Priority[]=['low','normal','high','urgent'];

type CreatePayload={title:string;description:string;assignee_id:string|null;priority:Priority;due_date:string|null;status:Status};
export default function EmployeeTaskBoard(){
 const {user,loading,configured,signIn,signOut}=useAuth();
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[register,setRegister]=useState(false),[authError,setAuthError]=useState(''),[busy,setBusy]=useState(false);
 const [profile,setProfile]=useState<Profile|null>(null),[profiles,setProfiles]=useState<Profile[]>([]),[tasks,setTasks]=useState<Task[]>([]),[loadingBoard,setLoadingBoard]=useState(false),[showCreate,setShowCreate]=useState(false),[error,setError]=useState(''),[drag,setDrag]=useState<string|null>(null);
 const isAdmin=profile?.role==='admin'||user?.app_metadata?.role==='admin';
 const load=async(u:typeof user)=>{if(!supabase||!u)return;setLoadingBoard(true);const {data:p}=await supabase.from('employee_profiles').select('id,name,email,role,access_enabled').eq('id',u.id).maybeSingle();const cp=p as Profile|null;setProfile(cp??{id:u.id,name:u.user_metadata?.name||u.email?.split('@')[0]||'Admin',email:u.email??null,role:u.app_metadata?.role==='admin'?'admin':'employee',access_enabled:u.app_metadata?.role==='admin'});const admin=cp?.role==='admin'||u.app_metadata?.role==='admin';if(admin){const [{data:people},{data:all}]=await Promise.all([supabase.from('employee_profiles').select('id,name,email,role,access_enabled').eq('role','employee').order('access_enabled').order('name'),supabase.from('employee_tasks').select('*').order('sort_order').order('created_at')]);setProfiles((people??[]) as Profile[]);setTasks((all??[]) as Task[]);}else if(cp?.access_enabled){const {data:own}=await supabase.from('employee_tasks').select('*').eq('assignee_id',u.id).order('sort_order').order('created_at');setTasks((own??[]) as Task[]);}setLoadingBoard(false);};
 useEffect(()=>{if(user)void load(user);else{setProfile(null);setProfiles([]);setTasks([])}},[user]);
 const create=async(p:CreatePayload)=>{if(!supabase||!isAdmin||!p.title.trim())return;setError('');const {data,error:e}=await supabase.from('employee_tasks').insert({...p,sort_order:Date.now()}).select('*').single();if(e){setError(e.message);return;}if(data){setTasks(x=>[...x,data as Task]);setShowCreate(false)}};
 const move=async(id:string,status:Status)=>{if(!supabase)return;const old=tasks;setTasks(x=>x.map(t=>t.id===id?{...t,status}:t));const {error:e}=await supabase.from('employee_tasks').update({status}).eq('id',id);if(e)setTasks(old)};
 const auth=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);setAuthError('');if(register){if(name.trim().length<2){setAuthError('Enter your full name.');setBusy(false);return}const {data,error:e}=await supabase.functions.invoke('employee-register',{body:{name:name.trim(),email:email.trim(),password}});if(e||data?.error)setAuthError(e?.message||data?.error||'Registration failed.');else setRegister(false)}else{const r=await signIn(email.trim(),password);if(r.error)setAuthError(r.error.message)}setBusy(false)};
 if(loading)return <Shell><div className="employee-board__loading">Checking session...</div></Shell>;
 if(!configured)return <Shell><div className="employee-board__empty"><span>SETUP REQUIRED</span><h1>Supabase is not configured.</h1></div></Shell>;
 if(!user)return <Shell><form className="employee-login" onSubmit={auth}><div className="employee-login__mark">ZERO ONE / TEAM</div><h1>{register?'Join the team.':'Team Board.'}</h1>{authError&&<div className="employee-login__error">{authError}</div>}{register&&<label>Full name<input required value={name} onChange={e=>setName(e.target.value)}/></label>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input required type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>{busy?'Please wait...':register?'Create account':'Sign in'}</button><button type="button" className="employee-login__switch" onClick={()=>{setRegister(!register);setAuthError('')}}>{register?'Already have an account? Sign in':'New employee? Create an account'}</button><a href="/admin">Admin sign in</a></form></Shell>;
 if(!isAdmin&&profile?.access_enabled!==true)return <Shell><div className="employee-access-pending"><div className="employee-board__eyebrow">ZERO ONE / TEAM ACCESS</div><div className="employee-access-pending__icon"><Clock3 size={22}/></div><h1>Waiting for approval.</h1><p>The admin needs to approve your access before you can enter the Team Board.</p><button className="employee-board__ghost" onClick={()=>void signOut()}><LogOut size={15}/> Sign out</button></div></Shell>;
 return <Shell><header className="employee-board__header"><div><div className="employee-board__eyebrow">ZERO ONE / TEAM WORKSPACE</div><h1>Task Board.</h1><p>{isAdmin?'Create and control as many custom cards as you need.':'Your assigned work lives here.'}</p></div><div className="employee-board__actions"><span className="employee-board__user"><UserRound size={15}/> {profile?.name||user.email}</span>{isAdmin&&<button className="employee-board__primary" onClick={()=>{setError('');setShowCreate(true)}}><Plus size={16}/> New Task</button>}<button className="employee-board__ghost" onClick={()=>void signOut()}><LogOut size={15}/> Sign out</button></div></header>
 {isAdmin&&<section className="employee-access-panel"><div className="employee-access-panel__head"><div><div className="employee-board__eyebrow">ACCESS CONTROL</div><h2>Employee approvals</h2></div><span>{profiles.filter(p=>!p.access_enabled).length} pending</span></div><div className="employee-access-panel__list">{profiles.length?profiles.map(p=><EmployeeRow key={p.id} person={p} onAccess={async v=>{if(!supabase)return;const {error:e}=await supabase.from('employee_profiles').update({access_enabled:v}).eq('id',p.id);if(!e)setProfiles(x=>x.map(i=>i.id===p.id?{...i,access_enabled:v}:i))}} onRename={async n=>{if(!supabase||n.trim().length<2)return;const {error:e}=await supabase.from('employee_profiles').update({name:n.trim()}).eq('id',p.id);if(!e)setProfiles(x=>x.map(i=>i.id===p.id?{...i,name:n.trim()}:i))}}/>):<div className="employee-access-panel__empty">No employee accounts yet.</div>}</div></section>}
 <div className="employee-board__toolbar"><div className="employee-board__legend"><span><i className="dot dot--orange"/> {tasks.length} tasks</span></div></div>
 {loadingBoard?<div className="employee-board__loading">Loading board...</div>:<div className="employee-board__scroll"><div className="employee-board__columns">{columns.map(c=>{const list=tasks.filter(t=>t.status===c.id);return <section key={c.id} className="employee-column" onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag){void move(drag,c.id);setDrag(null)}}}><div className="employee-column__head"><div><h2>{c.label}</h2><p>{c.sub}</p></div><span>{list.length}</span></div><div className="employee-column__cards">{list.map(t=><article key={t.id} draggable onDragStart={()=>setDrag(t.id)} onDragEnd={()=>setDrag(null)} className="employee-task"><div className="employee-task__top"><span className={`priority priority--${t.priority}`}>{t.priority}</span><GripVertical size={16}/></div><h3>{t.title}</h3>{t.description&&<p>{t.description}</p>}<div className="employee-task__meta">{isAdmin&&<span><UserRound size={12}/> {t.assignee_id?(profiles.find(p=>p.id===t.assignee_id)?.name||'Employee'):'Unassigned'}</span>}{t.due_date&&<span><Clock3 size={12}/> {new Date(`${t.due_date}T12:00:00`).toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}</span>}</div></article>)}</div>{isAdmin&&c.id==='client_requests'&&<button className="employee-column__add" onClick={()=>{setError('');setShowCreate(true)}}><Plus size={16}/> Add task</button>}</section>})}</div></div>}
 {showCreate&&isAdmin&&<CreateModal profiles={profiles.filter(p=>p.access_enabled)} error={error} onClose={()=>{setShowCreate(false);setError('')}} onCreate={create}/>}</Shell>;
}
function CreateModal({profiles,error,onClose,onCreate}:{profiles:Profile[];error:string;onClose:()=>void;onCreate:(p:CreatePayload)=>void}){const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[assignee,setAssignee]=useState(''),[priority,setPriority]=useState<Priority>('normal'),[due,setDue]=useState(''),[status,setStatus]=useState<Status>('client_requests');return <div className="employee-modal__backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><form className="employee-modal employee-create" onSubmit={e=>{e.preventDefault();onCreate({title,description,assignee_id:assignee||null,priority,due_date:due||null,status})}}><button type="button" className="employee-modal__close" onClick={onClose}><X size={18}/></button><div className="employee-modal__eyebrow">NEW TASK / CUSTOM CARD</div><h2>Create a card.</h2><p className="employee-modal__description">Assignment is optional. Create cards freely and assign them later.</p>{error&&<div className="employee-login__error" role="alert">{error}</div>}<div className="employee-create__grid"><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Assign to<select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Unassigned — assign later</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value as Priority)}>{priorities.map(p=><option key={p}>{p}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value as Status)}>{columns.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label></div><label>Description<textarea rows={5} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Due date<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><button className="employee-create__submit"><Plus size={16}/> Create card</button></form></div>}
function EmployeeRow({person,onAccess,onRename}:{person:Profile;onAccess:(v:boolean)=>Promise<void>;onRename:(n:string)=>Promise<void>}){const [edit,setEdit]=useState(false),[value,setValue]=useState(person.name);return <div className="employee-access-row"><div className="employee-access-row__identity">{edit?<div className="employee-access-row__edit"><input value={value} onChange={e=>setValue(e.target.value)}/><button onClick={()=>{void onRename(value);setEdit(false)}}><Save size={14}/></button></div>:<><strong>{person.name}</strong><small>{person.email||''}</small></>}</div><div className="employee-access-row__actions">{!edit&&<button className="employee-access-row__rename" onClick={()=>setEdit(true)}><Pencil size={13}/> Rename</button>}<button className={person.access_enabled?'employee-access-row__revoke':'employee-access-row__approve'} onClick={()=>void onAccess(!person.access_enabled)}>{person.access_enabled?'Revoke access':'Approve access'}</button></div></div>}
function Shell({children}:{children:React.ReactNode}){return <main className="employee-board-page">{children}</main>}