import { useEffect, useState } from 'react';
import { Plus, RefreshCw, Save, Trash2 } from 'lucide-react';
import { supabase } from '../lib/supabase';

type Override = { id: string; type: 'text' | 'link' | 'image'; target: string; value: string };
type SiteContent = { overrides: Override[] };
const empty: Override = { id: '', type: 'text', target: '', value: '' };
const input = 'w-full rounded-xl border border-[#F7F5F0]/10 bg-[#F7F5F0]/[0.03] px-4 py-3 text-sm outline-none focus:border-[#F14A0B]/70';
const button = 'inline-flex items-center justify-center gap-2 rounded-full border border-[#F7F5F0]/15 px-4 py-2.5 text-sm font-semibold transition hover:border-[#F14A0B]/50';

export default function SiteContentPanel() {
  const [items, setItems] = useState<Override[]>([]); const [draft, setDraft] = useState<Override>(empty); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState(false);
  const load = async () => { if (!supabase) return; setLoading(true); setError(''); const { data, error: e } = await supabase.from('site_content').select('content').eq('id','default').single(); if (e) setError(e.message); else { const content = (data?.content ?? {}) as SiteContent; setItems(Array.isArray(content.overrides) ? content.overrides : []); } setLoading(false); };
  useEffect(() => { void load(); }, []);
  const add = () => { if (!draft.target.trim() || !draft.value.trim()) { setError('Add the current value and the new value first.'); return; } setItems((x) => [...x, { ...draft, id: crypto.randomUUID(), target: draft.target.trim(), value: draft.value }]); setDraft(empty); setError(''); };
  const save = async () => { if (!supabase) return; setSaving(true); setError(''); const { error: e } = await supabase.from('site_content').upsert({ id:'default', content:{ overrides: items }, updated_at:new Date().toISOString() }); if (e) setError(e.message); else { setSaved(true); window.setTimeout(()=>setSaved(false),2200); window.dispatchEvent(new CustomEvent('zero-one:content-updated')); } setSaving(false); };
  return <section className="mt-10"><div className="mb-6 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-[#F14A0B] text-xs font-bold uppercase tracking-[0.2em]">Site CMS</p><h2 className="mt-2 text-2xl font-bold tracking-tight">Everything editable.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#F7F5F0]/45">Change any visible text, footer/navigation label, link URL, or image URL without touching the code. Use the exact current value as the target, then enter the replacement.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className={button}><RefreshCw size={15}/> Refresh</button><button onClick={()=>void save()} disabled={saving} className="inline-flex items-center gap-2 rounded-full bg-[#F14A0B] px-5 py-2.5 text-sm font-semibold text-[#111111] disabled:opacity-50"><Save size={15}/> {saving?'Saving...':'Save changes'}</button></div></div>
    {saved && <div className="mb-5 rounded-xl border border-emerald-400/25 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-200">Saved. Public site will pick up the changes.</div>}
    {error && <div role="alert" className="mb-5 rounded-xl border border-red-400/30 bg-red-400/5 px-4 py-3 text-sm text-red-200">{error}</div>}
    <div className="border border-[#F7F5F0]/10 bg-[#F7F5F0]/[0.02] p-5 md:p-7"><div className="grid gap-3 md:grid-cols-[150px_1fr_1fr_auto] md:items-end"><label><span className="mb-2 block text-[10px] uppercase tracking-widest text-[#F7F5F0]/45">Type</span><select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as Override['type']})} className={input}><option value="text">Text</option><option value="link">Link URL</option><option value="image">Image URL</option></select></label><label><span className="mb-2 block text-[10px] uppercase tracking-widest text-[#F7F5F0]/45">Current value</span><input value={draft.target} onChange={e=>setDraft({...draft,target:e.target.value})} placeholder="Exact text / URL currently on site" className={input}/></label><label><span className="mb-2 block text-[10px] uppercase tracking-widest text-[#F7F5F0]/45">New value</span><input value={draft.value} onChange={e=>setDraft({...draft,value:e.target.value})} placeholder="What you want it to become" className={input}/></label><button onClick={add} className="inline-flex h-[46px] items-center justify-center gap-2 rounded-xl bg-[#F14A0B] px-4 font-semibold text-[#111111]"><Plus size={16}/> Add</button></div></div>
    <div className="mt-6 space-y-3">{loading ? <div className="border border-[#F7F5F0]/10 p-8 text-sm text-[#F7F5F0]/45">Loading site content...</div> : items.length === 0 ? <div className="border border-dashed border-[#F7F5F0]/15 p-10 text-center"><p className="font-semibold">No overrides yet.</p><p className="mt-2 text-sm text-[#F7F5F0]/40">Add a text, link, or image replacement above.</p></div> : items.map((item,index)=><div key={item.id} className="grid gap-3 border border-[#F7F5F0]/10 bg-[#F7F5F0]/[0.02] p-4 md:grid-cols-[100px_1fr_1fr_auto] md:items-center"><span className="text-[10px] font-bold uppercase tracking-widest text-[#F14A0B]">{item.type}</span><div className="min-w-0"><p className="text-[10px] uppercase tracking-widest text-[#F7F5F0]/30">Current</p><p className="mt-1 break-words text-sm text-[#F7F5F0]/65">{item.target}</p></div><div className="min-w-0"><p className="text-[10px] uppercase tracking-widest text-[#F7F5F0]/30">Replacement</p><p className="mt-1 break-words text-sm font-semibold">{item.value}</p></div><button onClick={()=>setItems(x=>x.filter((_,i)=>i!==index))} className="inline-flex h-10 w-10 items-center justify-center rounded-full border border-red-400/20 text-red-200 hover:bg-red-400/10" aria-label="Remove override"><Trash2 size={15}/></button></div>)}</div>
    <p className="mt-6 text-xs leading-5 text-[#F7F5F0]/35">Tip: for footer links, use type <b>Link URL</b> and paste the current URL. For a footer label, use <b>Text</b>. For logos/photos, use <b>Image URL</b>.</p>
  </section>;
}
